# Generated by Django 6.0.7 on 2026-09-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_about_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='currently_learning',
            field=models.CharField(blank=True, help_text='Shown on the About page, e.g. React, APIs, cloud deployment', max_length=300),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Optional icon class. Leave blank for automatic Python/Django/HTML/CSS/etc. icon mapping.', max_length=60),
        ),
    ]
